# Generated by Django 5.0.6 on 2025-03-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Virtualapp", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(
                choices=[
                    ("General Inquiry", "General Inquiry"),
                    ("Collaboration inquiry", "Collaboration inquiry"),
                    ("Accounting inquiry", "Accounting inquiry"),
                    ("Marketing inquiry", "Marketing inquiry"),
                ],
                default="General Inquiry",
                max_length=50,
            ),
        ),
    ]
