# Generated by Django 5.0.6 on 2025-03-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Virtualapp", "0003_alter_contact_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "features",
                    models.TextField(help_text="Enter features separated by commas"),
                ),
                ("detailed_description", models.TextField()),
            ],
        ),
    ]
