# Generated by Django 5.0.6 on 2025-03-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Virtualapp", "0004_package"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("heading", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="uploads/")),
                ("button_name", models.CharField(max_length=100)),
                ("button_link", models.URLField()),
            ],
        ),
    ]
