# Generated by Django 5.0.6 on 2025-03-26 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Virtualapp", "0005_contentsection"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContentSection",
            new_name="Section1",
        ),
    ]
