# Generated by Django 5.0.6 on 2025-03-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Virtualapp", "0006_rename_contentsection_section1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section1",
            name="button_link",
            field=models.CharField(max_length=50),
        ),
    ]
