# Generated by Django 5.0.6 on 2025-03-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Virtualapp", "0007_alter_section1_button_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("business_name", models.CharField(max_length=255)),
                (
                    "collaboration_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("entrepreneur", "Food Entrepreneur"),
                            ("cloud-kitchen", "Cloud Kitchen"),
                            ("delivery-platform", "Delivery Platform"),
                            ("influencer", "Influencer / Chef"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
