# Generated by Django 5.0.6 on 2025-03-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Virtualapp", "0008_collaboration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collaboration",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="collaboration_type",
            field=models.CharField(
                choices=[
                    ("restaurant", "Restaurant"),
                    ("entrepreneur", "Food Entrepreneur"),
                    ("cloud-kitchen", "Cloud Kitchen"),
                    ("delivery-platform", "Delivery Platform"),
                    ("influencer", "Influencer / Chef"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
