# Generated by Django 5.0.6 on 2025-04-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Virtualapp", "0009_remove_collaboration_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("package_name", models.CharField(max_length=255)),
                ("package_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("package_id", models.IntegerField()),
            ],
        ),
    ]
