# Generated by Django 5.0.6 on 2025-04-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Virtualapp", "0010_checkout"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="service_images/")),
                ("heading", models.CharField(max_length=255)),
                (
                    "subheading",
                    models.TextField(
                        help_text="Limit to approximately 3 lines of text."
                    ),
                ),
                ("url", models.CharField(max_length=100, verbose_name="url")),
            ],
        ),
    ]
