# Generated by Django 5.0.6 on 2025-04-22 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Virtualapp", "0011_servicehome"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
    ]
