# Generated by Django 5.0.6 on 2025-04-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Virtualapp", "0013_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="company_type",
            field=models.CharField(
                default="Owner",
                help_text="e.g. Founder, Multi-Outlet Chain Owner",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
