# Generated by Django 5.0.6 on 2025-04-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Virtualapp", "0015_consultation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_image", models.ImageField(upload_to="brand_images/")),
                ("brand_name", models.CharField(max_length=255)),
                ("short_description", models.TextField(max_length=500)),
                ("swiggy_url", models.URLField(max_length=500)),
                ("zomato_url", models.URLField(max_length=500)),
            ],
        ),
    ]
